#Note:charleschan<hollidgelongsun157@gmail.com> made great efforts for OpenGNB porting to OpenWRT platform and provides technical supoort.
GNB_CFLAGS=$(CFLAGS) -ffunction-sections -fdata-sections -Wno-unused-result -I./src -I./libs -I./libs/miniupnpc -I./libs/libnatpmp -I./libs/zlib -D NO_GZIP=1 -D GNB_OPENWRT_BUILD=1
GNB_LDFLAGS=-Wl,--gc-sections -L/usr/lib
GNB_ES_LDFLAGS=-Wl,--gc-sections -L/usr/lib

ifeq ($(DEBUG),1)
GNB_CFLAGSS += -g
else
GNB_CFLAGS += -O2
GNB_LDFLAGS    += -s
GNB_ES_LDFLAGS += -s
endif

GNB_CRYPTO=gnb_crypto
GNB_CTL=gnb_ctl
GNB_ES=gnb_es
GNB=gnb

include Makefile.inc

GNB_OBJS =                                  \
        ./src/cli/gnb.o                     \
        ./src/gnb_argv.o                    \
        ./src/unix/unix_platform.o          \
        ./src/linux/gnb_drv_linux.o

GNB_ES_OBJS += ./src/unix/unix_platform.o

all: $(GNB) $(GNB_CTL) $(GNB_CRYPTO) $(GNB_ES)

$(GNB_CTL): $(GNB_CTL_OBJS)
	$(CC) -o $(GNB_CTL) $(GNB_CTL_OBJS) $(GNB_LDFLAGS)

$(GNB_ES): $(GNB_ES_OBJS) $(CRYPTO_OBJS) $(MINIUPNP_OBJS) $(LIBNATPMP_OBJS)
	${CC} -o $(GNB_ES) $(GNB_ES_OBJS) $(CRYPTO_OBJS) $(MINIUPNP_OBJS) $(LIBNATPMP_OBJS) $(GNB_ES_LDFLAGS) -pthread

$(GNB_CRYPTO): $(CRYPTO_OBJS) ./src/cli/gnb_crypto.o
	$(CC) -o $(GNB_CRYPTO) ./src/cli/gnb_crypto.o $(CRYPTO_OBJS) $(GNB_LDFLAGS)

$(GNB): $(GNB_OBJS) $(GNB_CORE_OBJS) $(GNB_PF_OBJS) $(CRYPTO_OBJS) $(ZLIB_OBJS)
	$(CC) -o $(GNB) $(GNB_OBJS) $(GNB_CORE_OBJS) $(GNB_PF_OBJS) $(CRYPTO_OBJS) $(ZLIB_OBJS) $(GNB_LDFLAGS) -pthread

%.o:%.c
	$(CC) $(GNB_CFLAGS) -c -o $@ $<

install: $(GNB) $(GNB_CTL) $(GNB_CRYPTO) $(GNB_ES)
	mkdir -p         ./bin/
	cp $(GNB)        ./bin/
	cp $(GNB_CTL)    ./bin/
	cp $(GNB_CRYPTO) ./bin/
	cp $(GNB_ES)     ./bin/

clean:
	find . -name "*.o" -exec rm -f {} \;
	rm -f $(GNB) $(GNB_CTL) $(GNB_CRYPTO) $(GNB_ES)
	rm -f core core.*
	rm -f *.exe
