ifeq ($(origin CC),default)
CC=gcc
endif

WINDRES ?= windres

GNB_CPPFLAGS=-I./src -I./libs -I./libs/wintun -I./libs/miniupnpc -I./libs/libnatpmp -I./libs/zlib -D NO_GZIP=1 -DMINIUPNP_STATICLIB -DNATPMP_STATICLIB

CLI_LDFLAGS=-static -lwsock32 -lws2_32 -liphlpapi -lpthread -lmingwex
GNB_ES_LDFLAGS=-static -lwsock32 -lws2_32 -liphlpapi -lpthread -lmingwex

ifeq ($(DEBUG),1)
CFLAGS += -g
else
CFLAGS += -O2
CLI_LDFLAGS += -s
GNB_ES_LDFLAGS += -s
endif

GNB_CRYPTO=gnb_crypto.exe
GNB_CTL=gnb_ctl.exe
GNB_ES=gnb_es.exe
GNB_CLI=gnb.exe


include Makefile.inc

.PHONY: all install clean

GNB_CLI_OBJS =                             \
       ./src/cli/gnb.o                     \
       ./src/gnb_argv.o                    \
       ./src/mingw/gnb_res.o               \
       ./src/mingw/windows_platform.o      \
       ./src/mingw/gnb_drv_win32.o         \
       ./src/mingw/gnb_drv_wintun.o

GNB_ES_OBJS += ./src/mingw/windows_platform.o

all:${GNB_CLI} ${GNB_CRYPTO} ${GNB_ES} ${GNB_CTL}


${GNB_CTL}: ${GNB_CTL_OBJS} ./src/mingw/gnb_res.o
	${CC} -o ${GNB_CTL} ${GNB_CTL_OBJS} ./src/mingw/gnb_res.o ${LDFLAGS} ${CLI_LDFLAGS}


${GNB_ES}: ${GNB_ES_OBJS} ${CRYPTO_OBJS} ${MINIUPNP_OBJS} ${LIBNATPMP_OBJS} ./src/mingw/gnb_res.o
	${CC} -o ${GNB_ES} ${GNB_ES_OBJS} ${CRYPTO_OBJS} ${MINIUPNP_OBJS} ${LIBNATPMP_OBJS} ./src/mingw/gnb_res.o ${LDFLAGS} ${GNB_ES_LDFLAGS}


$(GNB_CRYPTO): $(CRYPTO_OBJS) ./src/cli/gnb_crypto.o
	${CC} -o ${GNB_CRYPTO} ./src/cli/gnb_crypto.o ${CRYPTO_OBJS} ${LDFLAGS} ${CLI_LDFLAGS}


${GNB_CLI}: ${GNB_OBJS} ${GNB_CLI_OBJS} ${GNB_PF_OBJS} ${CRYPTO_OBJS} ${ZLIB_OBJS}
	${CC} -o ${GNB_CLI} ${GNB_OBJS} ${GNB_CLI_OBJS} ${GNB_PF_OBJS} ${CRYPTO_OBJS} ${ZLIB_OBJS} ${LDFLAGS} ${CLI_LDFLAGS}


%.o:%.c
	${CC} ${GNB_CPPFLAGS} ${CPPFLAGS} ${CFLAGS} -c -o $@ $<

./src/mingw/gnb_res.o: ./src/mingw/gnb_res.rc
	${WINDRES} ./src/mingw/gnb_res.rc -o ./src/mingw/gnb_res.o


install:${GNB_CLI} ${GNB_CRYPTO} ${GNB_ES} ${GNB_CTL}
	mkdir -p         ./bin/
	cp ${GNB_CLI}    ./bin/
	cp ${GNB_CTL}    ./bin/
	cp ${GNB_CRYPTO} ./bin/
	cp ${GNB_ES}     ./bin/

clean:
	find . -name "*.o" -exec rm -f {} \;
	rm -f ${GNB_CLI} ${GNB_CRYPTO} ${GNB_ES} ${GNB_CTL}
	rm -f core
	rm -f *.exe

