#Makefile.openwrt is only used for compiling and building on the OpenWRT platform.
#Note:charleschan<hollidgelongsun157@gmail.com> made great efforts for OpenGNB porting to OpenWRT platform and provides technical supoort.

GNB_CFLAGS=$(CFLAGS) -I./src -I./libs -D_GNU_SOURCE -DNO_GZIP=1 -DWITHOUT_MINIUPNPC -DGNB_SKIP_BUILD_TIME=1 -DGNB_OPENWRT_BUILD=1
GNB_LDFLAGS=$(LDFLAGS)
GNB_ES_LDFLAGS=$(LDFLAGS)

GNB_ES=gnb_es
GNB_CRYPTO=gnb_crypto
GNB_CTL=gnb_ctl
GNB=gnb

include Makefile.openwrt.inc

GNB_OBJS =                                  \
        ./src/cli/gnb.o                     \
        ./src/gnb_argv.o                    \
        ./src/unix/unix_platform.o          \
        ./src/linux/gnb_drv_linux.o

GNB_ES_OBJS += ./src/unix/unix_platform.o

all: $(GNB) $(GNB_CTL) $(GNB_CRYPTO) $(GNB_ES)

$(GNB_ES): $(GNB_ES_OBJS) $(CRYPTO_OBJS)
	$(CC) -o $(GNB_ES) $(GNB_ES_OBJS) $(CRYPTO_OBJS) $(GNB_ES_LDFLAGS) -pthread

$(GNB_CRYPTO): $(CRYPTO_OBJS) ./src/cli/gnb_crypto.o
	$(CC) -o $(GNB_CRYPTO) ./src/cli/gnb_crypto.o $(CRYPTO_OBJS) $(GNB_LDFLAGS)

$(GNB_CTL): $(GNB_CTL_OBJS)
	$(CC) -o $(GNB_CTL) $(GNB_CTL_OBJS) $(GNB_LDFLAGS)

$(GNB): $(GNB_OBJS) $(GNB_CORE_OBJS) $(GNB_PF_OBJS) $(CRYPTO_OBJS)
	$(CC) -o $(GNB) $(GNB_OBJS) $(GNB_CORE_OBJS) $(GNB_PF_OBJS) $(CRYPTO_OBJS) $(GNB_LDFLAGS) -lz -pthread

%.o:%.c
	$(CC) $(GNB_CFLAGS) -c -o $@ $<

install: $(GNB) $(GNB_CRYPTO) $(GNB_ES) $(GNB_CTL)
	mkdir -p         ./bin/
	cp $(GNB)        ./bin/
	cp $(GNB_CTL)    ./bin/
	cp $(GNB_CRYPTO) ./bin/
	cp $(GNB_ES)     ./bin/

clean:	
	find . -name "*.o" -exec rm -f {} \;
	rm -f $(GNB) $(GNB_CTL) $(GNB_CRYPTO) $(GNB_ES)
	rm -f core
	rm -f *.exe
