GNB_CFLAGS=$(CFLAGS) -O2 -I./src -I/usr/x86_64-w64-mingw32/include -I./libs -I./libs/wintun -I./libs/miniupnpc -I./libs/libnatpmp -I./libs/zlib -D NO_GZIP=1 -DMINIUPNP_STATICLIB -DNATPMP_STATICLIB

GNB_LDFLAGS=-s -static -L/usr/x86_64-w64-mingw32/lib/ -lwsock32 -lws2_32 -liphlpapi -lpthread -lmingwex
GNB_ES_LDFLAGS=-s -static -L/usr/x86_64-w64-mingw32/lib/ -lwsock32 -lws2_32 -liphlpapi -lpthread -lmingwex

GNB_CRYPTO=gnb_crypto.exe
GNB_CTL=gnb_ctl.exe
GNB_ES=gnb_es.exe
GNB_CLI=gnb.exe

include Makefile.inc

GNB_OBJS =                                 \
       ./src/cli/gnb.o                     \
       ./src/gnb_argv.o                    \
       ./src/mingw/gnb_res.o               \
       ./src/mingw/windows_platform.o      \
       ./src/mingw/gnb_drv_win32.o         \
       ./src/mingw/gnb_drv_wintun.o

GNB_ES_OBJS += ./src/mingw/windows_platform.o

all: $(GNB) $(GNB_CTL) $(GNB_CRYPTO) $(GNB_ES)

$(GNB_CTL): $(GNB_CTL_OBJS) ./src/mingw/gnb_res.o
	$(CC) -o $(GNB_CTL) $(GNB_CTL_OBJS) ./src/mingw/gnb_res.o $(GNB_LDFLAGS)

$(GNB_ES): $(GNB_ES_OBJS) $(CRYPTO_OBJS) $(MINIUPNP_OBJS) $(LIBNATPMP_OBJS)
	$(CC) -o ${GNB_ES} $(GNB_ES_OBJS) $(CRYPTO_OBJS) $(MINIUPNP_OBJS) $(LIBNATPMP_OBJS) ./src/mingw/gnb_res.o $(GNB_ES_LDFLAGS)

$(GNB_CRYPTO): $(CRYPTO_OBJS) ./src/cli/gnb_crypto.o
	$(CC) -o $(GNB_CRYPTO) ./src/cli/gnb_crypto.o $(CRYPTO_OBJS) $(GNB_LDFLAGS)

$(GNB): $(GNB_OBJS) $(GNB_CORE_OBJS) $(GNB_PF_OBJS) $(CRYPTO_OBJS) $(ZLIB_OBJS)
	$(CC) -o $(GNB) $(GNB_OBJS) $(GNB_CORE_OBJS) $(GNB_PF_OBJS) $(CRYPTO_OBJS) $(ZLIB_OBJS) $(GNB_LDFLAGS)

%.o:%.c
	$(CC) $(GNB_CFLAGS) -c -o $@ $<

./src/mingw/gnb_res.o: ./src/mingw/gnb_res.rc
	$(WINDRES) ./src/mingw/gnb_res.rc -o ./src/mingw/gnb_res.o

install: $(GNB) $(GNB_CTL) $(GNB_CRYPTO) $(GNB_ES)
	mkdir -p         ./bin/
	cp $(GNB)        ./bin/
	cp $(GNB_CTL)    ./bin/
	cp $(GNB_CRYPTO) ./bin/
	cp $(GNB_ES)     ./bin/

clean:
	find . -name "*.o" -exec rm -f {} \;
	rm -f $(GNB) $(GNB_CTL) $(GNB_CRYPTO) $(GNB_ES)
	rm -f core
	rm -f *.exe
